name: node-digital
on: 
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup node jobs
      uses: actions/setup-node@v3
      with: 
        node-version: '16'

    - name: install dependencies
      run: npm install
  
  docker-push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout
      #- name: setup buildx
       # uses: actions/setup-buildx-action@v1
      - name: login to docker-push
        uses: actions/login-action@v3
        with: 
          username: ameen2607
          password: dragonball.999

      - name: build and push
        uses: actions/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ameen2607/node-digital:${{github.run_id}}


      
