name: node-digital
on: 
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup node jobs
      uses: actions/setup-node@v3
      with: 
        node-version: '16'

    - name: install dependencies
      run: npm install

      
